---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/table-criteria/table-criteria.xlsx
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/176118/articles/212065/master/file/figures/table-criteria/table-criteria.xlsx"
